package com.chefcontrol.domain.audit;

public enum AuditAction {

    // Auth
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_RESTAURANT_SWITCHED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    RESTAURANT_REGISTERED,

    // Users
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    USER_REACTIVATED,

    // Restaurants
    RESTAURANT_CREATED,
    RESTAURANT_UPDATED,
    RESTAURANT_DEACTIVATED,

    // Suppliers
    SUPPLIER_CREATED,
    SUPPLIER_UPDATED,
    SUPPLIER_DEACTIVATED,

    // Products
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DEACTIVATED,

    // Purchases
    PURCHASE_CREATED,

    // Waste
    WASTE_EVENT_CREATED,

    // Stock
    STOCK_MOVEMENT_CREATED,
    STOCK_MOVEMENT_CORRECTED,
    STOCK_MOVEMENT_REVERSED,
    STOCK_COUNT_CREATED,

    // Recipes
    RECIPE_CREATED,
    RECIPE_UPDATED,
    RECIPE_DELETED,

    // Sales
    SALE_RECORDED,
    SALE_DELETED,

    // WhatsApp
    WHATSAPP_SESSION_STARTED,
    WHATSAPP_MESSAGE_PROCESSED,
    WHATSAPP_UNREGISTERED_ATTEMPT,

    // POS (Fase 5)
    POS_SYNC_COMPLETED,
    POS_SYNC_FAILED,

    // System
    SYSTEM,
}
