package com.chefcontrol.domain.audit;

public enum AuditAction {

    // Auth
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_RESTAURANT_SWITCHED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    RESTAURANT_REGISTERED,

    // Users
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    USER_PERMISSIONS_UPDATED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,

    // Restaurants
    RESTAURANT_CREATED,
    RESTAURANT_UPDATED,
    RESTAURANT_DEACTIVATED,
    RESTAURANT_ACTIVATED,
    RESTAURANT_DELETED,
    ACCOUNT_RENAMED,

    // Suppliers
    SUPPLIER_CREATED,
    SUPPLIER_UPDATED,
    SUPPLIER_DEACTIVATED,

    // Products
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DEACTIVATED,

    // Purchases
    PURCHASE_CREATED,
    PURCHASE_UPDATED,
    PURCHASE_REVERSED,

    // Waste
    WASTE_EVENT_CREATED,

    // Stock
    STOCK_MOVEMENT_CREATED,
    STOCK_MOVEMENT_CORRECTED,
    STOCK_MOVEMENT_REVERSED,
    STOCK_COUNT_CREATED,

    // Recipes
    RECIPE_CREATED,
    RECIPE_UPDATED,
    RECIPE_DELETED,

    // Sales
    SALE_RECORDED,
    SALE_REVERSED,
    SALE_DELETED,

    // Menu items
    MENU_ITEM_CREATED,
    MENU_ITEM_UPDATED,
    MENU_ITEM_DEACTIVATED,
    MENU_ITEM_REACTIVATED,
    MENU_ITEM_BULK_DEACTIVATED,
    MENU_ITEM_IMAGE_UPDATED,
    MENU_ITEM_IMAGE_DELETED,

    // Pasos del menú
    MENU_SECTION_CREATED,
    MENU_SECTION_UPDATED,
    MENU_SECTION_DELETED,
    MENU_SECTIONS_REORDERED,

    // Cartas
    CARTA_CREATED,
    CARTA_UPDATED,
    CARTA_DELETED,
    CARTA_ITEMS_ADDED,
    CARTA_ITEMS_REMOVED,

    // WhatsApp
    WHATSAPP_SESSION_STARTED,
    WHATSAPP_MESSAGE_PROCESSED,
    WHATSAPP_UNREGISTERED_ATTEMPT,

    // POS (Fase 5)
    POS_SYNC_COMPLETED,
    POS_SYNC_FAILED,

    // System
    SYSTEM,
}
